#!/bin/bash

# This script configures and starts the isc-dhcp-server on Ubuntu.
# WARNING: DO NOT RUN THIS SCRIPT ON macOS.

# --- Configuration ---
INTERFACE="eth2"
SERVER_IP="10.40.0.1"
SUBNET_MASK="20"
SUBNET="10.40.0.0"
NETMASK="255.255.240.0"
RANGE_START="10.40.0.2"
RANGE_END="10.40.15.255"
ROUTER_IP="10.40.0.1"
DNS_SERVERS="8.8.8.8, 8.8.4.4"

# 1. Check for root privileges
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo "--- Step 1: Passed root check ---"

# 2. Install isc-dhcp-server if not installed
if ! dpkg -l | grep -q "isc-dhcp-server"; then
    echo "isc-dhcp-server not found. Installing..."
    apt-get update
    apt-get install -y isc-dhcp-server
else
    echo "isc-dhcp-server is already installed."
fi

echo "--- Step 2: Completed package check/installation ---"

# 3. Configure static IP for the interface
echo "Configuring static IP ${SERVER_IP}/${SUBNET_MASK} on ${INTERFACE}..."
# Flush existing IPs to avoid conflicts
ip addr flush dev ${INTERFACE}
# Add the new static IP
ip addr add ${SERVER_IP}/${SUBNET_MASK} dev ${INTERFACE}

echo "--- Step 3: Completed static IP configuration ---"

# 4. Create dhcpd.conf
echo "Generating /etc/dhcp/dhcpd.conf..."
cat <<EOF > /etc/dhcp/dhcpd.conf
# DHCP Server Configuration File
# Generated by Gemini

# Option definitions
option domain-name "example.org";
option domain-name-servers ${DNS_SERVERS};

default-lease-time 600;
max-lease-time 7200;

# Use this to enable / disable dynamic dns updates globally.
ddns-update-style none;

# This DHCP server is the official DHCP server for this network.
authoritative;

# Subnet declaration
subnet ${SUBNET} netmask ${NETMASK} {
  range ${RANGE_START} ${RANGE_END};
  option routers ${ROUTER_IP};
}
EOF

echo "--- Step 4: Completed dhcpd.conf generation ---"

# 5. Configure the interface for isc-dhcp-server
echo "Configuring isc-dhcp-server to listen on ${INTERFACE}..."
if [ -f /etc/default/isc-dhcp-server ]; then
    sed -i 's/^INTERFACESv4=.*/INTERFACESv4="'${INTERFACE}'"/' /etc/default/isc-dhcp-server
else
    echo "Warning: /etc/default/isc-dhcp-server not found. This might be an issue on newer systems."
    # On newer Ubuntu versions (18.04+), you might need to configure /etc/netplan
    # or systemd-networkd, but for isc-dhcp-server, the default file is standard.
fi

echo "--- Step 5: Completed interface configuration ---"

# 6. Restart and check status of the DHCP server
echo "Restarting isc-dhcp-server..."
systemctl restart isc-dhcp-server

echo "--- Step 6: Service restarted. Checking status... ---"
systemctl status isc-dhcp-server
